In [3]:
%load_ext autoreload
%autoreload 2

import pandas as pd

from evaluate import run_evaluation_lin_tests
from evaluate import test_numeric_baseline, test_ordinal_baseline, test_binary_baseline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [4]:
df = pd.read_csv("data/evaluation/flores.csv", index_col=0)
df.head()

  static_id     model iso_639_3  persona  score
0  flores_0  qwen3-4b       ace  helpful      2
1  flores_1  qwen3-4b       ace  helpful      0
2  flores_2  qwen3-4b       ace  helpful      0
3  flores_3  qwen3-4b       ace  helpful      2
4  flores_4  qwen3-4b       ace  helpful      0

In [12]:
results = test_numeric_baseline(df)
results.summary()

<class 'statsmodels.iolib.summary2.Summary'>
"""
                    Mixed Linear Model Regression Results
=============================================================================
Model:                    MixedLM       Dependent Variable:       score
No. Observations:         115200        Method:                   REML
No. Groups:               8             Scale:                    0.1209
Min. group size:          14400         Log-Likelihood:           -41851.3952
Max. group size:          14400         Converged:                Yes
Mean group size:          14400.0
-----------------------------------------------------------------------------
                                   Coef.  Std.Err.   z    P>|z| [0.025 0.975]
-----------------------------------------------------------------------------
Intercept                           0.229    0.093  2.459 0.014  0.047  0.412
C(persona)[T.beginner_teacher]      0.004    0.005  0.809 0.418 -0.006  0.014
C(persona)[T.dynamic_long]          0.010    0.005  2.013 0.044  0.000  0.020
C(persona)[T.dynamic_medium]        0.006    0.005  1.266 0.205 -0.003  0.016
C(persona)[T.dynamic_short]         0.008    0.005  1.557 0.120 -0.002  0.018
C(persona)[T.expert_teacher]        0.008    0.005  1.619 0.105 -0.002  0.018
C(persona)[T.helpful]               0.010    0.005  1.930 0.054 -0.000  0.020
C(persona)[T.intermediate_teacher]  0.016    0.005  3.134 0.002  0.006  0.026
C(persona)[T.no]                   -0.003    0.005 -0.519 0.604 -0.012  0.007
C(persona)[T.static_long]           0.010    0.005  1.992 0.046  0.000  0.020
C(persona)[T.static_medium]         0.003    0.005  0.623 0.534 -0.007  0.013
C(persona)[T.static_short]          0.005    0.005  0.975 0.329 -0.005  0.015
Group Var                           0.070    0.110
=============================================================================

"""

In [7]:
df = pd.read_csv("data/evaluation/ifbench.csv")
df["persona"].unique()

array(['base', 'no', 'helpful', 'dynamic_medium', 'dynamic_short',
       'expert_teacher', 'static_long', 'intermediate_teacher',
       'static_short', 'beginner_teacher', 'static_medium',
       'dynamic_long'], dtype=object)

In [8]:
df = run_evaluation_lin_tests()

flores
Optimization terminated successfully.
         Current function value: 0.848914
         Iterations: 35
         Function evaluations: 37
         Gradient evaluations: 37
Optimization terminated successfully.
         Current function value: 0.772929
         Iterations: 31
         Function evaluations: 33
         Gradient evaluations: 33
Optimization terminated successfully.
         Current function value: 0.834287
         Iterations: 35
         Function evaluations: 37
         Gradient evaluations: 37
Optimization terminated successfully.
         Current function value: 0.886621
         Iterations: 37
         Function evaluations: 39
         Gradient evaluations: 39
Optimization terminated successfully.
         Current function value: 0.901479
         Iterations: 34
         Function evaluations: 36
         Gradient evaluations: 36
Optimization terminated successfully.
         Current function value: 0.806355
         Iterations: 35
         Function evaluations: 37
         Gradient evaluations: 37
ifbench
Optimization terminated successfully.
         Current function value: 0.537689
         Iterations 6
mmlu-pro
Optimization terminated successfully.
         Current function value: 0.382398
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.372995
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.419768
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.339486
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.354007
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.378402
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.356288
         Iterations 10
alpaca

/home/nico/miniconda3/envs/master-thesis/lib/python3.12/site-packages/statsmodels/regression/mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

MATH
Optimization terminated successfully.
         Current function value: 0.296339
         Iterations 9
Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.197008
         Iterations: 35
Optimization terminated successfully.
         Current function value: 0.220329
         Iterations 10

/home/nico/miniconda3/envs/master-thesis/lib/python3.12/site-packages/statsmodels/base/model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

Optimization terminated successfully.
         Current function value: 0.308541
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.242554
         Iterations 10
Optimization terminated successfully.
         Current function value: 0.346539
         Iterations 8

In [9]:
df

,dataset,subset_column,subset_value,term,coef,stderr,pvalue
0,flores,None,None,C(persona)[T.beginner_teacher],-0.850473,0.032186,7.266873e-154
1,flores,None,None,C(persona)[T.dynamic_long],0.354184,0.031005,3.190064e-30
2,flores,None,None,C(persona)[T.dynamic_medium],0.341569,0.030976,2.836619e-28
3,flores,None,None,C(persona)[T.dynamic_short],0.359170,0.030985,4.535803e-31
4,flores,None,None,C(persona)[T.expert_teacher],0.126991,0.030889,3.936617e-05
...,...,...,...,...,...,...,...
345,MATH,subject,Prealgebra,C(model)[T.gpt-5-nano],4.063313,0.183348,8.035656e-109
346,MATH,subject,Prealgebra,C(model)[T.llama-3-2-1b-instruct],-0.712236,0.292326,1.483242e-02
347,MATH,subject,Prealgebra,C(model)[T.llama-3-2-3b-instruct],0.255883,0.227308,2.602886e-01
348,MATH,subject,Prealgebra,C(model)[T.qwen3-0-6b],0.109651,0.234357,6.398694e-01
349,MATH,subject,Prealgebra,C(model)[T.qwen3-4b],0.343601,0.223460,1.241376e-01

In [ ]:
from evaluate import test_binary_baseline

df = pd.read_csv("data/evaluation/mmlu-pro.csv")

results = test_binary_baseline(df)
results.summary()

In [ ]:
results["persona"]